### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable

### ISSUE THREAD

**Issue by richardgmcmahon** [dhroth/count_quasars#1]
Hi Daniel,

This is not urgent since I can run in laptop or directly on Linux desktop but remotely running on Linux will be needed. I would be turning of the real time plots and just saving them in these runs

I think this is just a X11 backend issue but I am not sure how deep it is. One work around that I use to to us the Agg backend and not make X11 plots.

echo $DISPLAY is returnng empty string

best regards Richard

See traceback:

(lsst-sims) rgm@calx067(/data/vault/rgm/github/count_quasars){999}> python countQuasars.py --s
Traceback (most recent call last):
  File "countQuasars.py", line 131, in <module>
    plt.semilogy(limitingDepths, mu, color=zColor, label="z>=" + str(zCutoff))
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3409, in semilogy
    ax = gca()
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/pyplot.py", line 962, in gca
    return gcf().gca(**kwargs)
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/pyplot.py", line 592, in gcf
    return figure()
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 177, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 35, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 235, in __init__
    _create_qApp()
  File "/data/vault/rgm/anaconda2/envs/lsst-sims/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 122, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

**Comment by dhroth** [comment]
Hm, I thought I had fixed it to work without an X11 session running, but perhaps that was for another project. Changing the backend should work, and hopefully it won't mess up the plots. You're welcome to issue a PR with the change, otherwise I'll change it when I get back.

**Comment by dhroth** [comment]
Did changing the back-end work? I don't have an easy way to test this code on a headless server with no X11 session and would like to close this issue if the problem can be fixed by changing to Agg.
